### ISSUE TITLE
can events be added to the calendar?

### ISSUE THREAD

**Issue by wiiiimm** [davidalekna/react-organizer#1]
I see that there are events: boolean in a few views, but how do I pass the actual events into the component?

**Comment by d4lek** [comment]
Hi @williamli, events should be controlled from outside of the component, so you need to hold a state outside, and just pass those in as an array of events into the Organizer component. Here is an example repo - https://github.com/davidalekna/organizer-examples/blob/master/src/index.js

let me know if you have more questions 👍🏻

**Comment by wiiiimm** [comment]
I was looking for the definition of `event` object.
I found it in https://github.com/davidalekna/organizer-examples/blob/master/src/helpers/index.js <https://github.com/davidalekna/organizer-examples/blob/master/src/helpers/index.js>

Thanks.

**Comment by d4lek** [comment]
No worries mate. This package is being moved to a monorepo and is in a progress on being rewritten in typescript. 

https://github.com/davidalekna/react-components/tree/master/packages/alekna-organizer
